---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mosquitto-secret
    template:
      engineVersion: v2
      data:
        mosquitto_pwd: |
          {{ .MOSQUITTO_USERNAME }}:{{ .MOSQUITTO_PASSWORD }}
          {{ .MOSQUITTO_TESLAMATE_USERNAME }}:{{ .MOSQUITTO_TESLAMATE_PASSWORD }}
  dataFrom:
    - extract:
        key: mosquitto
