---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objstore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: thanos-objstore-secret
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: thanos
            endpoint: minio.network.svc.cluster.local:9000
            access_key: "{{ .MINIO_ACCESS_KEY }}"
            secret_key: "{{ .MINIO_SECRET_KEY }}"
            insecure: true
  dataFrom:
    - extract:
        key: minio
