---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      unpoller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.11.2
            env:
              TZ: "Europe/Paris"
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_UNIFI_DEFAULT_SAVE_SITES: true
              UP_UNIFI_DEFAULT_SAVE_DPI: true
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - secretRef:
                  name: unifi-poller-secret
            resources:
              requests:
                cpu: 5m
                memory: 36M
              limits:
                memory: 128M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
    service:
      app:
        controller: unpoller
        ports:
          http:
            port: 9130
    serviceMonitor:
      unpoller:
        serviceName: app
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
