---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: linkwarden-secret
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: linkwarden
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LINKWARDEN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LINKWARDEN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        # App
        DATABASE_URL: "postgresql://{{ .LINKWARDEN_POSTGRES_USER }}:{{ .LINKWARDEN_POSTGRES_PASSWORD }}@postgres-rw.databases.svc.cluster.local:5432/linkwarden"
        # Auth
        NEXT_PUBLIC_KEYCLOAK_ENABLED: "true"
        NEXTAUTH_SECRET: "{{ .LINKWARDEN_NEXTAUTH_SECRET }}"
        NEXTAUTH_URL: "https://linkwarden.oxygn.dev/api/v1/auth"
        KEYCLOAK_CUSTOM_NAME: "Authelia"
        KEYCLOAK_ISSUER: "https://auth.oxygn.dev"
        KEYCLOAK_CLIENT_ID: "{{ .LINKWARDEN_OIDC_CLIENT_ID }}"
        KEYCLOAK_CLIENT_SECRET: "{{ .LINKWARDEN_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: linkwarden
