---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      linkwarden:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: linkwarden-secret
        containers:
          app:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.6.0
            env:
              NEXT_PUBLIC_DISABLE_REGISTRATION: "true"
              NEXT_PUBLIC_CREDENTIALS_ENABLED: "false"
              DISABLE_NEW_SSO_USERS: "false"
              STORAGE_FOLDER: "config" # Will always end up as /data/STOREAGE_FOLDER so eg /data/config
              HOME: /data/config
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: linkwarden
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.oxygn.dev
        hosts:
          - host: "linkwarden.oxygn.dev"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: linkwarden
        globalMounts:
          - path: /data/config
      next-cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /data/.next/cache
      tmp:
        type: emptyDir
