---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1l24hqm8nmspcmpnxzx9y2xhxdmntg3x6m09an0alvjutkrgszcmqqld7zt"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1l24hqm8nmspcmpnxzx9y2xhxdmntg3x6m09an0alvjutkrgszcmqqld7zt"
