---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  BOOTSTRAP_CONFIG_FILE: "{{.ROOT_DIR}}/config.yaml"
  KUBECONFIG_FILE: "{{.KUBERNETES_DIR}}/main/kubeconfig"
  MAKEJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/makejinja.toml"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"
  # Binaries
  PYTHON_BIN: python3

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  PYTHONDONTWRITEBYTECODE: "1"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  bootstrap: .taskfiles/Bootstrap
  external-secrets: .taskfiles/ExternalSecrets
  flux: .taskfiles/Flux
  kubernetes: .taskfiles/Kubernetes
  postgres: .taskfiles/Postgres
  rook: .taskfiles/Rook
  sops: .taskfiles/Sops
  talos: .taskfiles/Talos
  volsync: .taskfiles/VolSync
  workstation: .taskfiles/Workstation

tasks:

  default:
    silent: true
    cmd: task -l
