---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  CLUSTER: '{{.CLUSTER | default "main"}}'
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'

env:
  KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.CLUSTER_DIR}}/bootstrap/talos/clusterconfig/talosconfig'

includes:
  bootstrap: .taskfiles/Bootstrap
  external-secrets: .taskfiles/ExternalSecrets
  flux: .taskfiles/Flux
  kubernetes: .taskfiles/Kubernetes
  rook: .taskfiles/Rook
  sops: .taskfiles/Sops
  talos: .taskfiles/Talos
  volsync: .taskfiles/VolSync
  workstation: .taskfiles/Workstation

tasks:

  default:
    cmd: task --list
    silent: true

  # Ref: https://github.com/go-task/task/issues/608
  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
