---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-vpn-secret
    template:
      engineVersion: v2
      data:
        OPENVPN_USER: "{{ .OPENVPN_USER }}"
        OPENVPN_PASSWORD: "{{ .OPENVPN_PASSWORD }}"
  dataFrom:
    - extract:
        key: privado-vpn
