---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        # Admin User
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASS }}"
        # Teslamate
        TESLAMATE_DB_USERNAME: "{{ .TESLAMATE_DB_USERNAME }}"
        TESLAMATE_DB_PASSWORD: "{{ .TESLAMATE_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: teslamate
