---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        # App
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: &dbHost postgres-rw.databases.svc.cluster.local.:5432
        GF_DATABASE_USER: &dbUser "{{ .GRAFANA_DB_USERNAME }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GRAFANA_DB_PASSWORD }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GRAFANA_OIDC_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OIDC_CLIENT_SECRET }}"
        # Admin User
        GF_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        GF_ADMIN_PASS: "{{ .GRAFANA_ADMIN_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local.
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        # Teslamate
        TESLAMATE_DB_USERNAME: "{{ .TESLAMATE_DB_USERNAME }}"
        TESLAMATE_DB_PASSWORD: "{{ .TESLAMATE_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: grafana
    - extract:
        key: teslamate