---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prometheus-pve-exporter
spec:
  staticConfigs:
    - targets:
      - 10.10.0.50  # Proxmox VE node.
      - 10.10.0.51  # Proxmox VE node.
  metricsPath: /pve
  params:
    module: ["default"]
    cluster: ["1"]
    node: ["1"]
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: pve-exporter.observability:9221  # PVE exporter.