---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: actions-runner-controller-auth-secret
    template:
      engineVersion: v2
      data:
        github_app_id: |-
          {{ .GITHUB_APP_ID }}
        github_app_installation_id: |-
          {{ .GITHUB_APP_INSTALLATION_ID }}
        github_app_private_key: |-
          {{ .GITHUB_APP_PRIVATE_KEY }}
        github_app_secret_token: |-
          {{ .GITHUB_APP_SECRET_TOKEN }}
  dataFrom:
    - extract:
        key: actions-runner-controller