---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: gha-runner-scale-set-controller
      namespace: dev
  values:
    nameOverride: gha-runner-scale-set
    runnerScaleSetName: gha-runner-scale-set
    githubConfigUrl: https://github.com/nea0d/homelab-ops
    githubConfigSecret: &secret actions-runner-controller-auth-secret
    minRunners: 1
    maxRunners: 6
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.318.0@sha256:9b49b75f291b4227462d8df8adb6f46f56fb18f9a3baf6b8a1fca60852a565a1
            command: ["/home/runner/run.sh"]
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: dev
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
