---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./claim.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # Templates
  - ../../../../../shared/templates/volsync/full
  - ../../../../../shared/templates/gatus/external
