---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./teslamate/ks.yaml