---
web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: true
security:
  oidc:
    issuer-url: "https://auth.oxygn.dev"
    redirect-url: "https://status.oxygn.dev/authorization-code/callback"
    client-id: "${GATUS_OIDC_CLIENT_ID}"
    client-secret: "${GATUS_OIDC_CLIENT_SECRET}"
    scopes: ["openid"]
ui:
  title: Status | Gatus
  header: Status
alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.oxygn.dev
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
  - name: flux-webhook
    group: external
    url: https://flux-webhook.oxygn.dev
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: discord
