---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: atuin-secret
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: |-
          postgres://{{ .ATUIN_POSTGRES_USER }}:{{ .ATUIN_POSTGRES_PASSWORD }}@postgres-rw.databases.svc.cluster.local/atuin
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .ATUIN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .ATUIN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: atuin
    - extract:
        key: cloudnative-pg