# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bitwarden-secrets-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bitwarden-secrets-manager:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ripplefcl/bws-cache
              tag: v2.3.0@sha256:73ad42472d3babebe99473a1c7945f4c25fc99e2df10000309895cbdcd535a7b
            env:
              SECRET_TTL: 3600
              DEBUG: "false"
              ORG_ID:
                valueFrom:
                  secretKeyRef:
                    name: bws-secret
                    key: ORG_ID
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources: &resources
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 100Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000
