apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:EC3loDyVFmabBKDq8tvMKtjasBPpjjABUYvsWAhf9yQDzEdAPkvkBw==,iv:SIlRlStHhDozDMDcXNZxfT6zwlkHO6itGdnLT8fjYN8=,tag:eJFx0Pdy07wV7hnbtgQiKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l24hqm8nmspcmpnxzx9y2xhxdmntg3x6m09an0alvjutkrgszcmqqld7zt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ29CZCthdjU0b3J0WDc3
            aWIzWWZVSVkwbXhYWlhGRnlJZVdIQlIrM1dNCmhQWmwwQWdJSzZJcFdFNC9FRXJo
            Z2xaWGxmRGhrNzJHYXNCMHp0WFhLUkEKLS0tIG8yL0xIY0tjSXRNM2hGL2NlQzBa
            VFRseFpNc0FXSTJjZHQwaE5HNHpMcTQKXgsYvCQBQWxxCEswlUgMhlBgamUh1plH
            Xi5cjjZi/gczNLLkkB2Yk6OIidvkjgqWjCgq/wecWbH24dhgcCcMSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T13:06:24Z"
    mac: ENC[AES256_GCM,data:Q4CQiVf1bTUI5ycGMgDCh0dmB2LAVJ1w5HZfZPnYKGxKGX/CqrSYlb/irJoPiCe/93rpQd1yv511VvbnusJucz3tHfSOnlcOZ0x2/lgQlehvDeyvSSXfQzzzIc6ZV25GK9Zo5zhexnHKdnCpEv/tcDRwuOC352NabjWMMHgQaWs=,iv:SGKPRLkLTnME1wphQC5bUpMMXDY+2NXlk5VJb70A9cw=,tag:SjwB3jP9n5dFb8ZqlQrVww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
