apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EmD9zw3ic8G4,iv:02aFEBnmEBbE14HTWbGhmBgKT2+HbGd+Q5iP9OhgCE0=,tag:AAJUhTmll79yN9QE8k7KPw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MhB4eWXSaDhPv6jzuVf7,iv:PKMA5VCk4GPbbGeucnzIpk1ZImcrWIRTX/GX9L5ZFVE=,tag:qu3tWvHHcT5dsei3HC8lYQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:htOR2tWtwkSNc5gFOhdjHY20kyn8gZYW5qKsyDSEtXNf9CVQ,iv:oZlDjp22x8FtRdvV29Muh0vHTr1ilDr0OxvwvK269BY=,tag:PkB23qXIeMyO+aw3cG5iAQ==,type:str]
    SECRET_BITWARDEN_ORG_ID: ENC[AES256_GCM,data:ml5f4Fk4EXlMVHB0eVKLaZtzp9RoJJZ/7l1Z/HfTzIzoShJ3,iv:vW3Is+DVXpFDPYORM3eEVKOmHfrnZU6rcoPPK202m5g=,tag:tisc5aYz3vlRaodxBT4TWA==,type:str]
    SECRET_BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:rlpNdJNRbiI+VXs64SaCVYGxsfO8mqPN91XLA52JGlc8m4mm,iv:lrU9PTXw9ET2qTtkdfGS2UX5H6OUkbTnIeIeM2UsM7s=,tag:J1G2aG7hU39DA8EKEoFfMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l24hqm8nmspcmpnxzx9y2xhxdmntg3x6m09an0alvjutkrgszcmqqld7zt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWndxa3JBU2cyZmh2NmVm
            dzgzMFZDSENWZEJZZnJqM1pKamtTemdqZlQ4CmNkU3NvczBESmgxOVdLWHRHRXU1
            ckp1My9NN2oxSnY4R1I0eGJ6c0ZZMEUKLS0tIEtPeEZQdmR2anhUUVZGNnVHaXRI
            Mm56YWZFRzRkMDZJa015VzB3UlRFL1kKWawoB7efWhYXdoLPA6N1wrrDnOnFpVAc
            kJKKRypfmNhgvgoWmvXwEVj+a2XB1COkOyjS+UTIG54h79W3W9c9YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T14:17:47Z"
    mac: ENC[AES256_GCM,data:7Jj9QbfPjERXQ9QBBvUVmGMoe1DnHaOUIIbSG+9but7IHWUWWdjnOTAgaJqBkGPcFJUPu5cJxNuOb/+M00JNIRusZaFQpqj1GZinYWGz7YBWfix12uuTXUPMh9QVpx4z49PJDQKhbG1GEvqazYw20ialBmMp96PFK6rA730VRHI=,iv:hqB1s1xixNPD3Z9nw0pxF3D+1g2jhBkJK0CMcK4nNjU=,tag:3/bfwStiwMMGLWUlCV/6fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
