---
apiVersion: 1
datasources:
  - name: TeslaMate
    type: postgres
    access: proxy
    url: postgres-r.databases.svc.cluster.local.:5432
    database: "teslamate"
    user: "$${TESLAMATE_DB_USERNAME}"
    secureJsonData:
      password: "$${TESLAMATE_DB_PASSWORD}"
    jsonData:
      sslmode: disable
      postgresVersion: 1000
      timeInterval: 30s