---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: readarr-secret
    template:
      engineVersion: v2
      data:
        # App
        READARR__AUTH__APIKEY: "{{ .READARR_API_KEY }}"
  dataFrom:
    - extract:
        key: readarr
