---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kapowarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      kapowarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mrcas/kapowarr
              tag: v1.0.0-beta-4
            env:
              TZ: Europe/Paris
            resources:
              requests:
                cpu: 15m
                memory: 256M
              limits:
                memory: 512M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5656
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Kapowarr
          gethomepage.dev/icon: calibre-web.png
          gethomepage.dev/description: Comic Downloads
          external-dns.alpha.kubernetes.io/target: internal.oxygn.dev
        hosts:
          - host: "kapowarr.oxygn.dev"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/db
      tmp:
        type: emptyDir
      data:
        type: nfs
        server: "10.10.10.20"
        path: "/volume2/Media"
        globalMounts:
          - path: /media
