---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: 'https://discord.com/app'
        - Gmail:
            - icon: gmail.png
              href: 'http://gmail.com'
        - Google Calendar:
            - icon: google-calendar.png
              href: 'https://calendar.google.com'
        - Outlook:
            - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/outlook.png
              href: 'https://outlook.com'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
        - Youtube Music:
            - icon: https://raw.githubusercontent.com/joryirving/home-ops/main/docs/src/assets/icons/youtube-music.png
              href: 'https://music.youtube.com'
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: 'https://reddit.com'
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - home-ops:
            - icon: github.png
              href: 'https://github.com/nea0d/home-ops'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel Status
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
              fields: ["status"]
        - Unifi:
            href: https://unifi.ui.com
            icon: unifi.png
            description: Unifi Dashboard
            widget:
              type: unifi
              url: https://unifi.oxygn.dev
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - Calendar:
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 7 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Radarr # service name for that widget
    - Infrastructure:
        - PVE-1:
            widget:
              type: proxmox
              url: https://pve.oxygn.dev
              username: {{HOMEPAGE_VAR_PVE_USER}}
              password: {{HOMEPAGE_VAR_PVE_PASS}}
              node: pve
        - PVE-2:
            widget:
              type: proxmox
              url: https://pve.oxygn.dev
              username: {{HOMEPAGE_VAR_PVE_USER}}
              password: {{HOMEPAGE_VAR_PVE_PASS}}
              node: pve2
        - PBS:
            href: https://pbs.oxygn.dev
            description: Proxmox Backup Server
            widget:
              type: proxmoxbackupserver
              url: https://pbs.oxygn.dev
              username: {{HOMEPAGE_VAR_PBS_USER}}
              password: {{HOMEPAGE_VAR_PBS_PASS}}
        - Synology:
            href: https://nas01.oxygn.dev
            icon: synology.png
            description: Synology NAS
            widget:
              type: diskstation
              url: https://nas01.oxygn.dev
              username: {{HOMEPAGE_VAR_SYNOLOGY_USER}}
              password: {{HOMEPAGE_VAR_SYNOLOGY_PASS}}
              volume: volume_2
    - Home:
        - Home-Assistant:
            href: https://hass.oxygn.dev
            icon: home-assistant.png
            description: Home Automation Software
            widget:
              type: homeassistant
              url: https://hass.oxygn.dev
              key: {{HOMEPAGE_VAR_HASS_TOKEN}}
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        style: row
        columns: 3
        icon: mdi-network
      Games:
        style: row
        columns: 3
        icon: mdi-minecraft
      Calendar:
        style: column
        icon: mdi-calendar
      Video:
        style: column
        icon: mdi-play-circle
      Books:
        style: row
        columns: 2
        icon: mdi-book
      Infrastructure:
        style: row
        columns: 5
        icon: mdi-server
      Observability:
        style: row
        columns: 5
        icon: mdi-chart-line
      Home:
        style: row
        columns: 5
        icon: mdi-home-analytics
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
  widgets.yaml: |
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Howdy Hey!"
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
          label: "main"
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        latitude: {{HOMEPAGE_VAR_HASS_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_HASS_LONGITUDE}}
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
    - unifi_console:
        url: https://unifi.oxygn.dev
        username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
