---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_TUNNELS_API_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNIFI_HOMEPAGE_USERNAME }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_HOMEPAGE_PASSWORD }}"
        HOMEPAGE_VAR_PVE_USER: "{{ .PVE_HOMEPAGE_USER }}"
        HOMEPAGE_VAR_PVE_PASS: "{{ .PVE_HOMEPAGE_PASS }}"
        HOMEPAGE_VAR_PBS_USER: "{{ .PBS_HOMEPAGE_USER }}"
        HOMEPAGE_VAR_PBS_PASS: "{{ .PBS_HOMEPAGE_PASS }}"
        HOMEPAGE_VAR_SYNOLOGY_USER: "{{ .DSM_HOMEPAGE_USER }}"
        HOMEPAGE_VAR_SYNOLOGY_PASS: "{{ .DSM_HOMEPAGE_PASS }}"
        ## Downloads
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .READARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        ## Home
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HOMEPAGE_VAR_HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        ## Media
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_SERVER_TOKEN }}"
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: grafana
    - extract:
        key: home-assistant
    - extract:
        key: lidarr
    - extract:
        key: overseerr
    - extract:
        key: plex
    - extract:
        key: prowlarr
    - extract:
        key: proxmox
    - extract:
        key: radarr
    - extract:
        key: readarr
    - extract:
        key: sabnzbd
    - extract:
        key: sonarr
    - extract:
        key: synology
    - extract:
        key: tautulli
    - extract:
        key: unifi