---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: lldap-secret
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName lldap
        INIT_POSTGRES_HOST: &dbHost postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser "{{ .LLDAP_DB_USERNAME }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .LLDAP_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
        #Lldap
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_USER_DN: "{{ .LLDAP_USER_DN }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        LLDAP_DATABASE_URL: "postgres://{{ .LLDAP_DB_USERNAME }}:{{ .LLDAP_DB_PASSWORD }}@postgres-rw.databases.svc.cluster.local/lldap"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: lldap