---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./gha-runner-scale-set/ks.yaml
  - ./gha-runner-scale-set-controller/ks.yaml

