---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: discord
            repeat_interval: 12h
            routes:
              - receiver: "null"
                matchers:
                  - alertname="Watchdog"
              - receiver: "null"
                matchers:
                  - alertname="InfoInhibitor"
              - receiver: discord
                continue: true
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          receivers:
            - name: "null"
            - name: "discord"
              discord_configs:
                - webhook_url: "{{ .PROMETHEUS_HOOK }}"
                  send_resolved: true
                  title: |-
                    [{{ "{{" }} .Status | toUpper {{ "}}" }}{{ "{{" }} if eq .Status "firing" {{ "}}" }}:{{ "{{" }} .Alerts.Firing | len {{ "}}" }}{{ "{{" }} end {{ "}}" }}]
                    {{ "{{" }} .CommonLabels.alertname {{ "}}" }}
                  message: |-
                    {{ "{{-" }} range .Alerts {{ "}}" }}
                      {{ "{{-" }} if ne .Annotations.description "" {{ "}}" }}
                        {{ "{{" }} .Annotations.description {{ "}}" }}
                      {{ "{{-" }} else if ne .Annotations.summary "" {{ "}}" }}
                        {{ "{{" }} .Annotations.summary {{ "}}" }}
                      {{ "{{-" }} else if ne .Annotations.message "" {{ "}}" }}
                        {{ "{{" }} .Annotations.message {{ "}}" }}
                      {{ "{{-" }} else {{ "}}" }}
                        Alert description not available
                      {{ "{{-" }} end {{ "}}" }}
                      {{ "{{-" }} if gt (len .Labels.SortedPairs) 0 {{ "}}" }}
                        <small>
                        {{ "{{-" }} range .Labels.SortedPairs {{ "}}" }}
                          <b>{{ "{{" }} .Name {{ "}}" }}:</b> {{ "{{" }} .Value {{ "}}" }}
                        {{ "{{-" }} end {{ "}}" }}
                        </small>
                      {{ "{{-" }} end {{ "}}" }}
                    {{ "{{-" }} end {{ "}}" }}
  dataFrom:
    - extract:
        key: discord