---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: teslamate-secret
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        DATABASE_HOST: &dbHost postgres-rw.databases.svc.cluster.local.
        DATABASE_USER: &dbUser "{{ .TESLAMATE_DB_USERNAME }}"
        DATABASE_PASS: &dbPass "{{ .TESLAMATE_DB_PASSWORD }}"
        DATABASE_NAME: &dbName teslamate
        # Mosquitto
        MQTT_USERNAME: "{{ .MOSQUITTO_TESLAMATE_USERNAME }}"
        MQTT_PASSWORD: "{{ .MOSQUITTO_TESLAMATE_PASSWORD }}"
        #Postgres Init
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: mosquitto
    - extract:
        key: teslamate
