---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: pgadmin-secret
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL}}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"
  dataFrom:
    - extract:
        key: pgadmin
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: pgadmin-local-config
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: bitwarden-secrets-manager
#   target:
#     name: pgadmin-local-config-secret
#     template:
#       templateFrom:
#         - configMap:
#             name: pgadmin-local-config
#             items:
#               - key: config_local.py
#   dataFrom:
#     - extract:
#         key: pgadmin
