apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4Cd1KpAh5AsEnsP3B6jrLffpdBb9QTiHDPpbBvM0L8w=,iv:05h+9PZdLcFt2JC/7a/i5NjRmZKi7HP4EUU4liwZQgs=,tag:MLG0SGi56QSpezKgIlKn3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l24hqm8nmspcmpnxzx9y2xhxdmntg3x6m09an0alvjutkrgszcmqqld7zt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySzlwTlJJM0lPeUZJNVhj
            dnFTcWFZamw0Z2tpczJ4em43N052M0prNDFzCkVvTmNTNFFxdHp2NGZSdy9PcnVv
            TDJiNmVsVWFRNWM1NVA5VUxYRUwvUFUKLS0tIHM4MGtSbTJ1bjVBRVBxcG8wbC9M
            ZjhOUWxxK3Z6L25NWDFnM0czaU5kMmsKrmwisiTO59EaiCb3UqIfbiwoHeEpzmIb
            ZTTVxBBhf3YoOIDle0BpkiTqqG3PS1+BFpyhYUwPBcxlhjGEn/3+Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T11:28:49Z"
    mac: ENC[AES256_GCM,data:XhmsGh232MiAAbEtfFfF2STz0l+7+aGsDZH/smPMFlHt1hc1tj1yAB3LPnBZpnjYMipqS4QZay5DC5u+qd2oTHztlIpByoB9YnFlpF44GBM+UvzsbMuinhEVj+bhVGkNsB/8y5haR8zSbZLsDCRPolfvD5G0pW5+PHvCcMALRsM=,iv:ek81835lVDm3TXBJO8dbSxJeiG/+K6PeBKzdlQlnW3c=,tag:C6P6EGYAP23zHA3zbUjy8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
