# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: coder-secret
    coder:
      initContainers:
        - name: 01-init-db
          image: ghcr.io/onedr0p/postgres-init:16.3
          envFrom:
            - secretRef:
                name: &secret coder-secret
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 71m
      env:
        # DB
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: *secret
              key: CODER_PG_CONNECTION_URL
        # App
        - name: CODER_ACCESS_URL
          value: https://coder.oxygn.dev
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*.coder.oxygn.dev"
        # Disable password connections (only via OIDC - Authelia)
        - name: CODER_DISABLE_PASSWORD_AUTH
          value: "true"
        # Github
        - name: CODER_GITAUTH_0_ID
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_ID
        - name: CODER_GITAUTH_0_TYPE
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_TYPE
        - name: CODER_GITAUTH_0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_CLIENT_ID
        - name: CODER_GITAUTH_0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_GITAUTH_0_CLIENT_SECRET
        # OIDC
        - name: CODER_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: *secret
              key: CODER_OIDC_ISSUER_URL
        - name: CODER_OIDC_EMAIL_DOMAIN
          valueFrom:
            secretKeyRef:
              name: *secret
              key: CODER_OIDC_EMAIL_DOMAIN
        - name: CODER_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: *secret
              key: CODER_OIDC_CLIENT_ID
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secret
              key: CODER_OIDC_CLIENT_SECRET
      ingress:
        enable: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.oxygn.dev
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
        host: "coder.oxygn.dev"
