---
apiVersion: v1
kind: Service
metadata:
  name: &app funkstation
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: funkstation.internal
  # type: ClusterIP
  # clusterIP: None
  ports:
    - name: http-syno
      port: &port 5000
      protocol: TCP
      targetPort: *port
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: nas
#   namespace: network
# subsets:
#   - addresses:
#       - ip: 10.10.10.20
#     ports:
#       - name: http-syno
#         port: 5000
#         protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app funkstation
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: internal
  rules:
    - host: "funkstation.oxygn.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 5000
