---
apiVersion: v1
kind: Service
metadata:
  name: &app pbs
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: pbs.internal
  # type: ClusterIP
  # clusterIP: None
  ports:
    - name: https-pbs
      port: &port 8007
      protocol: TCP
      targetPort: *port
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: pbs
#   namespace: network
# subsets:
#   - addresses:
#       - ip: 10.10.10.23
#     ports:
#       - name: https-pbs
#         port: 8007
#         protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app pbs
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: internal
  rules:
    - host: "pbs.oxygn.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  name: "https-pbs"
