---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "External Secrets Sync"

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: Cluster Name
        default: main
        required: true
      externalSecretNamespace:
        description: External Secret Namespace
        default: security
        required: true
      bitwardenDeploymentName:
        description: Bitwarden Deployment Name
        default: bitwarden-secrets-manager
        required: true
  push:
    branches: ["main"]
    paths: ["kubernetes/**/externalsecret.yaml"]

jobs:
  sync:
    name: External Secrets Sync
    runs-on: ["gha-runner-scale-set"]
    steps:
      # - name: Get Secrets
      #   uses: bitwarden/sm-action@v2
      #   with:
      #     access_token: ${{ secrets.BW_ACCESS_TOKEN }}
      #     secrets: |
      #       3826e4d4-27f9-4f3e-8d36-b16000afabed > BOT_APP_ID
      #       29074be3-6f8f-4b6b-bc29-b16000b0a6cc > BOT_APP_PRIVATE_KEY
      #       0e922e6c-59a1-46d8-8d58-b16000b1ed15 > KUBECONFIG

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 0

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Workflow Tools
        shell: bash
        run: brew install kubernetes-cli

      - name: Write kubeconfig
        id: kubeconfig
        uses: timheuer/base64-to-file@v1
        with:
          encodedString: "${{ secrets.KUBECONFIG }}"
          fileName: kubeconfig

      - if: ${{ github.event.inputs.clusterName == '' && github.event.inputs.externalSecretNamespace == '' && github.event.inputs.bitwardenDeploymentName == '' }}
        name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: kubernetes/**/externalsecret.yaml
          safe_output: false

      - if: ${{ github.event.inputs.clusterName == '' && github.event.inputs.externalSecretNamespace == '' && github.event.inputs.bitwardenDeploymentName == '' }}
        name: List All Changed Files
        run: echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"

      - if: ${{ github.event.inputs.clusterName != '' && github.event.inputs.externalSecretNamespace != '' && github.event.inputs.bitwardenDeploymentName != '' }}
        name: Restart BWS Cache deployment
        env:
          KUBECONFIG: ${{ steps.kubeconfig.outputs.filePath }}
        shell: bash
        run: |
          kubectl rollout restart deployment ${{ github.event.inputs.bitwardenDeploymentName }} \
              --context ${{ github.event.inputs.clusterName }} \
              --namespace ${{ github.event.inputs.externalSecretNamespace }}